### ISSUE TITLE
第一次小组会议 20190330

### ISSUE THREAD

**Issue by happylyy** [livingworld/IA004_blockchain#1]
第一次小组会议来啦
时间 20190330 周六 上午10:00

讨论内容
1. 带领大家熟悉下团队协作工具
2. 参考现有的bp大纲，确定bp的目标：
    - 研究范围
    - 研究目的

阳老师建议：

分析公司战略控制指数，找到真正有贡献的公司，找到闷声发大财，而不是媒体广泛报道的公司。

后续问题：**如何找到有真正贡献的公司？**

于是策略调整为：作为一个智库人员，要对区块链领域写一份研报，该如如何做？作为一个投资人如果想要投资区块链领域，该如何选项目？从以下两个角度入手挖掘信息。

如何找到真有贡献的公司？

1. 找到区块链中高频的领域。媒体反复报道，学术反复研究。
   1. 国家政策反复强调
   2. 学术领域反复研究（这块是不是应该看看国外学术领域反复研究的是什么）
2. 找到投资区块链的大牛。
   1. 找到区块链领域投资人的全局。
   2. 按照 媒体不关注、博客 这些线索 比较出权重。
   3. 抽样或结构阅读文字信息，进行甄别。
3. 按照几个行业分析100家公司的战略投资指数
   1. 按照哪些维度来选取行业
   2. 分析哪些战略控制指数

**Comment by livingworld** [comment]
## 思路

### 知网区块链数据分析

- 硕博论文+核心期刊论文

由于在知网上，有关区块链的文章都较新，且都参差不齐，在本次分析中，为保证学术文献的可靠性，期刊方面选择了 SCI来源期刊、EI来源期刊、核心期刊、CSSCI、CSCD，并结合现有的硕博文献进行检索，以 `区块链` 为主题词进行检索，通过人工筛选，文献数量为，需要注意的是，部分引用率较高的文献由于不在相应的文献检索范围，所以在此处没有考虑，最后经过人工筛选，得到的文献总数约987篇。

![硕博](https://upload-images.jianshu.io/upload_images/637344-68c85abbd9ad5d6e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![期刊文献](https://upload-images.jianshu.io/upload_images/637344-645a5aff43f6e559.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**主题词**

从`LSI算法` 图中可以知道，国内有关于区块链的学术研究，大致可分为如图所示的11大类，分别是共识算法、财政金融、监管沙盒、互联网金融、能源互联网、金融科技、金融创新、数字货币、档案管理、区块链技术、金融机构、去中心化。

![LSI算法](https://upload-images.jianshu.io/upload_images/637344-1bb81f0f59c208c9.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


从`LLR算法` 图中可以知道，国内有关于区块链的学术研究，大致可分为如图所示的11大类，分别是共识算法、财政金融、风险、大数据、以太坊、金融科技、数字资产、数字货币、匿名性、联盟链、银行业、去中心化。

![LLR算法](https://upload-images.jianshu.io/upload_images/637344-a01aaf8aa1dc4428.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

从`MI算法` 图中可以知道，国内有关于区块链的学术研究，大致可分为如图所示的11大类，分别是跨域认证、商业信用、食品安全追溯、金融区块链、充电、沙箱监管、智能化、自由兑换、能源交易、税收征管、领域、数字出版权。

![MI算法图](https://upload-images.jianshu.io/upload_images/637344-b79c02e4b0f18c15.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

从 `Burst图` 看，突现点分别是比特币、金融、银行业、财政金融。

![Burst图](https://upload-images.jianshu.io/upload_images/637344-d39285d5aab26454.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**作者**

从作者分布上看，国内专门从事该领域研究的学者发文量还较少，相互之间的关联合作还较少。

![author](https://upload-images.jianshu.io/upload_images/637344-859fb52e5fb2377a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**机构**

从机构分布图上看，机构间的合作较少。

![institution](https://upload-images.jianshu.io/upload_images/637344-259ce1151fcf4040.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


## web of science 数据分析

以 `blockchain` 为主题词，进行检索，共得到约 1942 篇相关文献。

**出版年**

对下载下来的文献进行分析，文献样本时间为 2013 ——2019 。

![visualization_出版年.jpg](https://upload-images.jianshu.io/upload_images/637344-a02c15e228ce5d9e.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**国家分布**

可以看到，文献主要由美国、中国分列第一和第二位。

![visualization_国家.jpg](https://upload-images.jianshu.io/upload_images/637344-24a15f133559a824.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**文献类型**

![visualization_文献类型.jpg](https://upload-images.jianshu.io/upload_images/637344-34270287f3ed3562.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Category**

结合 web of science 自带的文献分析，从学科出现次数排列，区块链涉及了诸多学科，学科方向分别是:COMPUTER SCIENCE；ENGINEERING；TELECOMMUNICATIONS等诸多学科。

![visualization_研究方向.jpg](https://upload-images.jianshu.io/upload_images/637344-72579965d41cfc55.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

细部：

![image.png](https://upload-images.jianshu.io/upload_images/637344-63700dc0a6a8b483.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

再综合使用 citepace 科学计量工具对其进行分析，从学科分类上看，COMPUTER SCIENCE；COMPUTER SCIENCE, THEORY & METHODS；COMPUTER SCIENCE, INTERDISCIPLINARY APPLICATIONS（计算机科学；计算机科学、理论与方法；计算机科学、跨学科应用）具有突现性，说明这三个学科方向对区块链的发展有转折意义。

![Category.png](https://upload-images.jianshu.io/upload_images/637344-497bec6dba4744b7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**机构分布**

![visualization_机构.jpg](https://upload-images.jianshu.io/upload_images/637344-9577eba88c70369f.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

发文数量排名前 20 的研究机构分别是：CHINESE ACADEMY OF SCIENCES、BEIJING UNIVERSITY OF POSTS TELECOMMUNICATIONS、UNIVERSITY OF LONDON、INTERNATIONAL BUSINESS MACHINES IBM、UNIVERSITY OF CALIFORNIA SYSTEM、COMMONWEALTH SCIENTIFIC INDUSTRIAL RESEARCH ORGANISATION CSIRO、BEIHANG UNIVERSITY、UNIVERSITE PARIS SACLAY COMUE、UNIVERSITY OF NEW SOUTH WALES SYDNEY、CORNELL UNIVERSITY、NANYANG TECHNOLOGICAL UNIVERSITY、NANYANG TECHNOLOGICAL UNIVERSITY NATIONAL INSTITUTE OF EDUCATION NIE SINGAPORE、UNIVERSITY OF TEXAS SYSTEM、ETH ZURICH、NATIONAL UNIVERSITY OF DEFENSE TECHNOLOGY CHINA、PEKING UNIVERSITY、UNIVERSITY COLLEGE LONDON、UNIVERSITY OF CHINESE ACADEMY OF SCIENCES CAS、CENTRE NATIONAL DE LA RECHERCHE SCIENTIFIQUE CNRS、PENNSYLVANIA COMMONWEALTH SYSTEM OF HIGHER EDUCATION PCSHE（百度翻译：中国科学院、北京邮电大学、伦敦大学、国际商用机器IBM、加利福尼亚大学系统、联邦科学工业研究组织、北航大学、巴黎大学、新南威尔士大学悉尼分校、康奈尔大学、南洋理工大学、南洋理工大学新加坡国立教育学院、得克萨斯大学、苏黎世联邦理工大学、中国国防科技大学、北京大学、伦敦大学学院、中科院大学、国家科学研究中心、宾夕法尼亚联邦高等教育体系。）


**Reference**

借助 citespace 文献分析恭喜，对引用文献进行分析，共有 35988 篇引用文献，通过突现分析，可以看到NAKAMOTO S 于 2008 年发表的一篇名为 BITCOIN PEER TO PEER 的文章，这篇文章对该领域有重大影响，由于出现时间最早，可判断该文开启了区块链学术领域的研究。

![Burst](https://upload-images.jianshu.io/upload_images/637344-a3bc7ab6a82e10ab.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

通过 LLR 算法聚类分析，共分为9大类，分别为：business innovation 、blockchain technology、making smart contract 、empirical finding、homomorphic computation、bitcoin payment network、blockchain mining game、basing divesified service、bitcoin network、software connector（商业创新、区块链技术、智能合约制作、实证分析、同态计算、比特币支付网络、区块链挖矿游戏、基础剥离服务、比特币网络、软件连接件），从行业应用上看，并没有看出很鲜明的特征。

![image.png](https://upload-images.jianshu.io/upload_images/637344-3ef24bfa71a05f48.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Keyword**

对关键词部分进行分析，点击 `K`，在进一步采用 LLR、LSI、MI三种算法生成聚类标签。

![image.png](https://upload-images.jianshu.io/upload_images/637344-016b33c8b317ed43.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

通过 LLR 算法聚类，共分为 9 大类，分别为：fog computing、cloud computing、law、encryption、survey、transactive energy、machine learning、smart home、ontology、virtual currency（翻译：雾计算、云计算、法律、加密、调查、交易能源、机器学习、智能家居、本体论、虚拟货币）

通过 LSI 算法聚类，共分为9大类，分别为：fog computing、cloud computing、digital identity、things、internet、smart contracts、game theory、things、artificial intelligence（雾计算、云计算、数字身份、事物、互联网、智能合约、博弈论、事物、人工智能）

通过 MI 算法聚类，共分类9大类，分别为：trusted electronic record、block withholding、incidence relation、distributed databases、0、smart energy grid、decentralized iot、additive manufacturing、ipfs、classification of virtual currencies（可信电子记录、扣块、关联关系、分布式数据库、0、智能能源网格、分散物联网、增广制造、ipfs、虚拟货币分类）

综合上述聚类分析，从行业应用来看，主要涉及能源交易、法律、智能家居、人工智能、物联网等领域。

![cluster_K_LLR](https://upload-images.jianshu.io/upload_images/637344-c6fadc547e6f81b2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![cluster_K_LSI](https://upload-images.jianshu.io/upload_images/637344-fe6ccc4d0c1238c5.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![cluster_K_MI](https://upload-images.jianshu.io/upload_images/637344-b98c5141bc962b76.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

从突现上看，突现词分别为bitcoin、cryptocurrency、digital currency（比特币，加密货币，数字货币）

![Burst](https://upload-images.jianshu.io/upload_images/637344-79575fede7142dbf.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

从鱼眼图、时间线图上可以看到各研究方向的发展时间脉络：

![鱼眼图](https://upload-images.jianshu.io/upload_images/637344-97fbdf304d010b5a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![Timeline.png](https://upload-images.jianshu.io/upload_images/637344-2340072741373c92.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## ChangeLog
- 201903301911 add
- 201903300913 init

**Comment by happylyy** [comment]
## 20190330 第一次小组会议



## 摘要 

参加人员：hetao，朱婧，钟蓉，刘宇旸，王赓某，Moses，舟舟队长，火冰

内容要点：

1. 介绍bp整体进度和团队协作工具
2. Moses同学介绍对比特币的认识
3. 同学们共同探讨对区块链的理解



## 重点内容

1. BP整体进度和团队协作。

   1. 刘宇旸介绍了bp的整体进度，同学们在做bp的时候注意参考信息分析的阶段，在信息获取阶段发散思维脑力激荡收集尽量多的信息，在信息整理阶段注意及时收敛

2. 对区块链的认识

   1. Moses观察员介绍了他学到的[区块链开发课程](https://www.imooc.com/learn/1021)，介绍了对比特币的理解，认为是一种类似于投机市场的产物。比特币的价值在将能量转换成金钱，而比特币的溢价则属于市场对于新兴事物未来的预期，有投机的成分存在。
   2. 王赓某同学介绍他对于区块链的理解是价值互联网，举了李笑来的pressone是构建一个基于区块链的写作平台，在平台上写作的作者会被跟踪到他作品的每次阅读每次购买，直接从读者处获得收益。另外，谈了一下对于区块链目前的困境在于分布式账本的容量和账本的更新速度难以调和。
   3. 刘宇旸同学介绍了两个区块链行业应用案例。一是基于慈善领域的应用，一个是基于行政办事大厅的应用。
   4. 火冰观察员从区块链从业者的角度，介绍了抛开比特币以外的区块链。
      1. 区块链分为有币和无币。有币的区块链就是王赓某提到的李笑来pressone的例子，通过区块链进行价值传递；无币的区块链就是刘宇旸提到的两个行业应用案例。而从区块链从业者的角度来看无币的区块链并不能体现区块链作为价值互联网的属性。（这点和阳老师对于区块链的观点比较像，但是和了解到的政府政策不是很吻合，需要对中国政府的区块链政策做个最小全局认识）
      2. 比特币是区块链1.0时代，而比特币只是区块链的一个成熟的应用场景。接下来是区块链2.0时代，一个方向是以太坊，主要实现可编程金融；另一个方向是匿名币，隐私方案解决。
      3. 现在是区块链3.0时代，也就是价值互联网。区块链未来主流技术是主链上只存放最小信息，其他信息通过“隔离见证”来实现，具体技术有侧链，闪电网络等。目前比较成熟的应用是支付，游戏和赌博领域。

3. 界定BP的研究范围

   1. 在火冰同学发言之前，对临时大纲已经收敛到如下大纲：
      1. 技术的问题不是重点。
      2. 区块链行业应用的焦点在哪里？哪些应用是真正做实事的应用。
      3. 按照行业分析100家公司的战略控制指数 
         1. 按照哪些维度来选取行业
         2. 分析哪些战略控制指数
         3. 公司信息从哪里来
         4. 如何去挖掘到“闷声发大财的公司”
   2. 然而火冰同学给我们带了很多新的信息，认为我们研究区块链是不能绕过比特币的，建议将比特币放到区块链的历史里面介绍一下
      1. 区块链的由来
      2. 区块链的派别（有币，无币）
   3. 之前根据阳老师的建议，认为没有必要去了解区块链技术，直接去研究区块链公司就可以了。然而火冰同学认为还是需要了解区块链的底层技术架构，才能够对这个行业有深入的认识。

   综上，本次会议并没有确定BP的研究范围，而是约火冰同学给我们再做一次区块链的科普，再确定后续方向。同时这段时间，同学们分头从风投公司和靠谱的媒体中大量搜集区块链创业公司的信息，批量阅读。



## 后续行动

Action1: 大家各自发挥从风投公司和靠谱的媒体中收集区块链创业公司的信息。

可参考的信息来源：

https://www.block123.com

https://www.chainnews.com/articles/371926012135.htm

Action2: 约个时间由火冰给大家科普下区块链的发展和核心技术，大概需要30分钟。


## 疑问点

无



## ChangeLog

- 20190330 创建



## 参考资料

详情请参考[阳志平：专业主义，从备忘录开始](https://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=2651937363&idx=1&sn=97f6f2b8d593055f064b07e5578f47fa&chksm=8bcf1c4bbcb8955d32686b1191b66d6f0f2b0e774691ccc92fbcd2a3ecb73cf824ccf37a03b4&scene=7&ascene=0&devicetype=android-28&version=2700033b&nettype=WIFI&abtest_cookie=AwABAAoACwATAAQAI5ceAFaZHgDBmR4A3JkeAAAA&lang=zh_CN&pass_ticket=5YcaMOPlJiUS2PaPDjhTwTdepF1F4yY0uKlSWu5sv9DPuHF%2F%2BihYO5p59feMDwAE&wx_header=1)

**Comment by livingworld** [comment]
## 个人思考

根据组长的思路，我来谈谈个人理解。

首先要明确我们的目标是什么，我们不是去追逐行业的发展，也不是去了解区块链技术的发展脉络，我们是要锁定区块链的应用场景，挖掘出“闷声发大财的公司”或者此类公司所具有的潜质？如果是如此的话，那么，我们从以下角度出发：

1.在学术方向，通过检索 CNKI、WOS 等文献，采用 citespace 等工具进行分析，得到一些初步的印象，了解国内外区块链发展现状及存在的问题，并了解在应用领域主要聚焦的领域。这部分能够给我们提供什么样的指导，待思考。

2.专利检索，要不要再对区块链的专利技术应用建立个全局认识，比如有哪些领域的技术应用，找到相应的公司。能否给我们一定的指导，待思考。

3.政策上，梳理近几年国内（或国外）关于区块链出台过哪些文件，召开过哪些会议，政府重点支持哪些领域，抑制哪些领域，能否从政策倾向上，找到那些可能会产生出高贡献公司的行业。

4.投资人、企业或公司，国内可否借助it桔子、企查查等平台上检索区块链相关的信息，抓取投资人、企业等信息，了解国内区块链公司主要在做哪些方向，能否分门别类，帮助我们建立整理认识。结合政策导向、专利技术等，锁定一批公司。

5.我们对甄别出一批公司进行分析，发现公司背后的商业网络、公司基本信息、公司传统财务指标、公司战略控制指数。是否可行？

6.得出结论，区块链高价值公司特质是什么，相应的代表是什么？我们能提供什么样的指导建议。

**Comment by jingzhou9908** [comment]
> ## 个人思考
> 根据组长的思路，我来谈谈个人理解。
> 
> 首先要明确我们的目标是什么，我们不是去追逐行业的发展，也不是去了解区块链技术的发展脉络，我们是要锁定区块链的应用场景，挖掘出“闷声发大财的公司”或者此类公司所具有的潜质？如果是如此的话，那么，我们从以下角度出发：
> 
> 1.在学术方向，通过检索 CNKI、WOS 等文献，采用 citespace 等工具进行分析，得到一些初步的印象，了解国内外区块链发展现状及存在的问题，并了解在应用领域主要聚焦的领域。这部分能够给我们提供什么样的指导，待思考。
> 
> 2.专利检索，要不要再对区块链的专利技术应用建立个全局认识，比如有哪些领域的技术应用，找到相应的公司。能否给我们一定的指导，待思考。
> 
> 3.政策上，梳理近几年国内（或国外）关于区块链出台过哪些文件，召开过哪些会议，政府重点支持哪些领域，抑制哪些领域，能否从政策倾向上，找到那些可能会产生出高贡献公司的行业。
> 
> 4.投资人、企业或公司，国内可否借助it桔子、企查查等平台上检索区块链相关的信息，抓取投资人、企业等信息，了解国内区块链公司主要在做哪些方向，能否分门别类，帮助我们建立整理认识。结合政策导向、专利技术等，锁定一批公司。
> 
> 5.我们对甄别出一批公司进行分析，发现公司背后的商业网络、公司基本信息、公司传统财务指标、公司战略控制指数。是否可行？
> 
> 6.得出结论，区块链高价值公司特质是什么，相应的代表是什么？我们能提供什么样的指导建议。

可以跑一跑，搜集更多的资料~~~~，西部掘金者，赚钱的事卖水的，那么区块链这里，赚钱的人在哪里？

**Comment by happylyy** [comment]
把昨天王赓同学的建议也发过来，
1. 时刻提醒自己，咱们的目标是信息分析，建立区块链全局认识，找到关键的人、技术、公司、价值、应用
2. 比特币是第一种区块链应用，但不是全部
3. token不能和代币等同
4. 利益冲突、逻辑、成本思维，是判断观点的三大法宝
