### ISSUE TITLE
第二次小组会议 20190402

### ISSUE THREAD

**Issue by happylyy** [livingworld/IA004_blockchain#3]
第二次小组会议来啦
时间 20190402 周二 晚上7：42

会议内容：
1. 王赓同学自我介绍
2. hetao同学分享下sitespace的调查结果
3. 互助时间：对于区块链概念还有问题的同学提出来，互相解答（为了控制时间，有疑问请在后面跟帖）
4. 分享下bp的思路和现阶段信息收集的结果（有思路的同学在下面跟帖，届时按照跟帖顺序分享）。参考周日的答疑，可以按照下面的思考框架来分享：
   1. 信息收集过程中希望得到的答案，或者希望验证的假设。
   2. 信息收集的思路。
5. 确定bp输出目标，确定大纲，认领任务。

会议记录：hetao

PS：有问题有思路就先贴上来，可以快速拉平同学们基础知识的不足，后面几天如果已经自问自答或者思路有了更新可以跟帖。

**Comment by happylyy** [comment]
**BP希望得到的结论**：行业区块链领域的价值在哪里。有哪些代表性的公司。

**探索的问题：**

1. 中国政策是支持有token还是无token区块链？
2. 行业区块链应用是属于有token的还是无token的？
3. 行业区块链应用真正做的“实事”是什么？
4. 都有哪些真正做“实事”的公司？
5. 10年后区块链行业可能会是什么样？


**分析思路：**

1. 通过论文分析，得到区块链技术的研究热点。（hetao同学已经做了）
2. 研读国家区块链政策，界定中国区块链发展方向。进一步是参考国外的发展方向。国内各省市的政策基本都是跟着中央走，数据只能反映出地区政府的支持程度。（正在整理国内的部分）
3. 通过专利检索得到头部企业区块链应用的研究焦点。
4. 通过专门从事区块链产业的风投公司（如丰元资本，除此之外还有哪些风投公司？），以及行业媒体（见卡包[财经大数据](https://m.openmindclub.com/stu/IA004/content/a412b14e-f20a-4cd4-a57d-e342b3c4a20c)），了解整个行业对于区块链发展的方向以及优质公司。（这里如何分析战略控制指数和价值链尚不明确）

**Comment by happylyy** [comment]
> 
> ## 个人思考
> 
> 根据组长的思路，我来谈谈个人理解。
> 
> 首先要明确我们的目标是什么，我们不是去追逐行业的发展，也不是去了解区块链技术的发展脉络，我们是要锁定区块链的应用场景，挖掘出“闷声发大财的公司”或者此类公司所具有的潜质？如果是如此的话，那么，我们从以下角度出发：
> 
> 1.在学术方向，通过检索 CNKI、WOS 等文献，采用 citespace 等工具进行分析，得到一些初步的印象，了解国内外区块链发展现状及存在的问题，并了解在应用领域主要聚焦的领域。这部分能够给我们提供什么样的指导，待思考。
> 
> 2.专利检索，要不要再对区块链的专利技术应用建立个全局认识，比如有哪些领域的技术应用，找到相应的公司。能否给我们一定的指导，待思考。
> 
> 3.政策上，梳理近几年国内（或国外）关于区块链出台过哪些文件，召开过哪些会议，政府重点支持哪些领域，抑制哪些领域，能否从政策倾向上，找到那些可能会产生出高贡献公司的行业。
> 
> 4.投资人、企业或公司，国内可否借助it桔子、企查查等平台上检索区块链相关的信息，抓取投资人、企业等信息，了解国内区块链公司主要在做哪些方向，能否分门别类，帮助我们建立整理认识。结合政策导向、专利技术等，锁定一批公司。
> 
> 5.我们对甄别出一批公司进行分析，发现公司背后的商业网络、公司基本信息、公司传统财务指标、公司战略控制指数。是否可行？
> 
> 6.得出结论，区块链高价值公司特质是什么，相应的代表是什么？我们能提供什么样的指导建议。

何涛同学的思路基本差不多，通过提问应该可以继续深入

**Comment by happylyy** [comment]
> 
> 把昨天王赓同学的建议也发过来，
> 
>     1. 时刻提醒自己，咱们的目标是信息分析，建立区块链全局认识，找到关键的人、技术、公司、价值、应用
> 
>     2. 比特币是第一种区块链应用，但不是全部
> 
>     3. token不能和代币等同
> 
>     4. 利益冲突、逻辑、成本思维，是判断观点的三大法宝

王同学提到的token和代币不能等同，还不是很理解

**Comment by jingzom** [comment]
## 区块链价值焦点探索

思路：

- 1：通过研究报告寻找热点领域，关注的公司、投资人等

- 2：通过学术领域热点交叉验证

  

## 目前探索情况

- 通过元搜索引擎：http://www.webcrawler.com 查询，这个引擎还没被墙，不用梯子也能用google不了的同学可以参考

  block chain report sitefile:pdf

  查找热门帖子的编辑 进一步找风投公司等

- https://blockchainreport.com/ 在推出一些区块链的热点
  
  
  

## 思考

- 英语世界中应该也有类似于 http://ef.zhiweidata.com/#!/index 热点分析的网站，找到的话应该能够效率更高一些
- 

## ChangeLog

- 20190401 朱婧创建

**Comment by livingworld** [comment]
## 区块链的定义

>区块链技术起源于2008 年由化名为“中本聪”(Satoshi nakamoto) 的学者在密码学邮件组发表的奠基性论文《比特币: 一种点对点电子现金系统》，目前尚未形成行业公认的区块链定义。狭义来讲, 区块链是一种按照时间顺序将数据区块以链条的方式组合成特定数据结构, 并以密码学方式保证的不可篡改和不可伪造的去中心化共享总账(Decentral-ized shared ledger), 能够安全存储简单的、有先后关系的、能在系统内验证的数据. 广义的区块链技术则是利用加密链式区块结构来验证与存储数据、利用分布式节点共识算法来生成和更新数据、利用自动化脚本代码(智能合约) 来编程和操作数据的一种全新的去中心化基础架构与分布式计算范式。区块链具有去中心化、时序数据、集体维护、可编程和安全可信等特点。

- 出处：区块链技术发展现状与展望_2016

>区块链发展大致经历了三个阶段，从1.0时代的数字货币，到2.0时代的智能合约，再到3.0时代对区块链技术全面应用的畅想。区块链1.0是以比特币、莱特币等为代表的加密货币，是与转账、汇款和数字化支付相关的密码学货币应用；区块链2.0是以以太坊、瑞波币为代表的智能合约，是经济、市场和金融领域的区块链应用；区块链3.0是区块链技术在社会领域下的应用场景实现，为各种行业提供去中心化解决方案。

- 出处：亿欧智库 - 2018年区块链行业应用研究报告（上篇）

## 区块链行业应用领域的分类

- 金融：数字货币（比特币等）、供应链金融、跨境支付等；
- 娱乐：区块链游戏、区块链社交等；
- 法律：版权保护等；
- 溯源：食药畜牧、知识产权、数字凭证和供应链四个领域基于区块溯源的行业应用等；
- 公益：捐赠等；
- 物联网：农业产业、能源产业、其他产业物联网子链。
- ......

- 出处：亿欧智库 - 2018年区块链行业应用研究报告（上篇）

## 区块链学术领域的分析

### 中文文献

在中国知网上以 `区块链` 为关键词检索期刊学术信息，关于区块链的学术论文最早由杨晓晨、张明在2014发表在期刊《金融评论》上，文章名为《比特币:运行原理、典型特征与前景展望》。自此国内学者在该领域陆陆续续有了一些研究。国内该领域的研究正处于蓬勃发展的状态，近几年的年发文量超过千篇，但发文质量参差不齐，人工筛选的成本过高，权衡利弊，我们只需要通过对可靠文献进行分析，逼近国内区块链学术领域的最小全局认识即可。因此，在此次分析研究中，仅选择硕博学位论文和SCI来源期刊、EI期刊、核心期刊、CSSCI期刊、CSCD期刊，结合人工筛选，截止2019年3月31日，共筛选出学术论文1019篇，其中学位论文201篇。

#### 时间维度

| 时间 |文献数量分布 |文献累积量 |
| ------ | ------ | ------ |
| 2014 |  1| 1 |
| 2015|  3|  4|
| 2016 | 71 |75  |
| 2017 |  226|301  |
| 2018 |  567|  869|
| 2019 |  151| 1019 |

![文献数量分布](https://upload-images.jianshu.io/upload_images/637344-f5aa12d9f7c88f67.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![文献累积量](https://upload-images.jianshu.io/upload_images/637344-52572b46bc66df09.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

从时间上看，国内于2016年起呈现爆炸性增长，并以成倍的速度快速增长。

#### 空间维度

**作者**

使用文献计量工具 citespace 对文献作者进行进行分析，得到结果如下：

| 出现频次 |最早出现年份 |姓名 |
| ------ | ------ | ------ |
| 8|  2017| 祁兵|
| 8|  2017|  王飞跃|
| 8| 2017|李彬 |
| 7|  2017|朱建明  |
| 6|  2017| 袁勇|
| 6|  2016| 姚前|
| 5|  2017| 李德智 |

![作者.png](https://upload-images.jianshu.io/upload_images/637344-0ab110a3c3d98a49.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/540)

从表中可以看到，文献出现频次大于等于5的共有8位作者，分别是祁兵（8）、王飞跃（8）、李彬（8）、朱建明（7）、袁勇（6）、姚前（6）、李德智（5）。从作者的可视化图谱中可知，国内学者在区块链领域的研究相互合作较少，尚未形成大的关联网络。


**机构**

使用文献计量工具 citespace 对文献机构进行进行分析，得到结果如下：

| 出现频次 |最早出现年份 |机构 |
| ------ | ------ | ------ |
| 9|  2017| 中央财经大学信息学院|
| 8|  2017|  中国科学院自动化研究所复杂系统管理与控制国家重点实验室|
| 7| 2017|华北电力大学电气与电子工程学院 |
| 6 |  2017|武汉大学信息管理学院 |
| 5|  2017| 中国人民银行数字货币研究所|
| 5|  2017| 中国科学院大学中国经济与社会安全研究中心|
| 5|  2017| 国防科学技术大学军事计算实验与平行系统技术中心 |
| 5|  2018| 华北电力大学控制与计算机工程学院 |
| 5|  2017| 青岛智能产业技术研究院 |
| 5|  2017| 中国科学院大学 |
| 5|  2017| 东北大学计算机科学与工程学院 |
| 5|  2017| 上海大学管理学院 |


![机构.png](https://upload-images.jianshu.io/upload_images/637344-eb6757acc2171abf.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/800)

citespace 无法将同一学校机构下不同学院进行归并，所得结果并未反应大学机构整体情况，所以此处综合考虑知网检索工具，对相应文献来源进行分析，排名考前10的机构分别是：中国人民大学、清华大学、华北电力大学、中国科学院大学、中央财经大学、武汉大学、复旦大学、上海大学、北京大学、北京航空航天大学。

![institution.png](https://upload-images.jianshu.io/upload_images/637344-754367ea5439c820.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/800)

从机构分布图上看，机构间的合作较少。


#### 变量维度

**学科分布**

由于所选择的数据集无法进行学科分析，在此处结合[知网指数](http://kns.cnki.net/kns/brief/default_result.aspx?islist=1&code=CIDX&singleDBName=%e6%8c%87%e6%95%b0)进行分析，检索 `区块链`，可以知道，与区块链相关的主题涉及到多个学科，比如计算机软件及应用、金融、信息经济与邮政经济、贸易经济、企业经济、工业经济、宏观经济管理与可持续发展、投资、证券、保险等。

![学科分布](https://upload-images.jianshu.io/upload_images/637344-a8ab974c8417c629.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**关键词知识图谱**

关键词知识图谱能将本领域的研究前沿、研究的转折点以及研究热点领域较好展示出来。在 citespace 中，研究前沿、研究热点和研究转折点一般用突现词（Burst）、频次（Frequency）、中介中心性（Centrality）体现。

**研究热点**

频次的大小反映出学术领域的研究热点，筛选出行业应用领域出现频次大于或等于10的列表：

![Freq>=10](https://upload-images.jianshu.io/upload_images/637344-e42addbd9b3abf30.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

从中可以看到, 区块链在行业应用方面，主要分为以下几大类：

1、金融领域：数字货币、金融科技、互联网金融、金融、财政金融、金融机构、银行、供应链金融、金融创新、银行业、监管科技、商业银行等频次较高，这意味着金融是区块链行业应用领域的研究热点；
2、物联网：物联网的频次为19，且中介中心性为0.5，远大于0.1，这意味着物联网是区块链行业应用领域的热点；
3、供应链：供应链的频次为10，中介中心性为0.25，这意味着供应链是区块链行业应用领域的研究热点；
4、共享经济：共享经济的频次为10，中介中心性为0.13，这意味着共享经济是区块链行业应用领域的研究热点；
5、能源互联网：能源互联网的频次为16，说明这个领域也是学术研究的热点。

**前沿领域**

`Burst图` 是按照时间顺序排序的突现词演变，表明某一时段突然上升或突然下降的节点，这类节点能代表某一个时段的研究前沿。突现点分别是比特币、金融、银行业、财政金融、数字货币、互联网金融，表明这些关键词在一段时期内是行业研究的前沿。

![Burst图](https://upload-images.jianshu.io/upload_images/637344-1d746e41f8bf9750.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

### 外文文献

#### 时间维度


以 `blockchain` 为主题词，进行检索，共得到约 1942 篇相关文献。

**出版年**

对下载下来的文献进行分析，文献样本时间为 2013 ——2019 。

![visualization_出版年.jpg](https://upload-images.jianshu.io/upload_images/637344-a02c15e228ce5d9e.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

#### 空间维度

**国家分布**

文献中排名前五的国家分别是：美国（416）、中国（409）、英国（158）、德国（127）、意大利（105）、澳大利亚（92）。

![visualization_国家分布.jpg](https://upload-images.jianshu.io/upload_images/637344-24a15f133559a824.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**机构分布**

对机构进行分析，发文数量排名前 20 的研究机构分别是：CHINESE ACADEMY OF SCIENCES、BEIJING UNIVERSITY OF POSTS TELECOMMUNICATIONS、UNIVERSITY OF LONDON、INTERNATIONAL BUSINESS MACHINES IBM、UNIVERSITY OF CALIFORNIA SYSTEM、COMMONWEALTH SCIENTIFIC INDUSTRIAL RESEARCH ORGANISATION CSIRO、BEIHANG UNIVERSITY、UNIVERSITE PARIS SACLAY COMUE、UNIVERSITY OF NEW SOUTH WALES SYDNEY、CORNELL UNIVERSITY、NANYANG TECHNOLOGICAL UNIVERSITY、NANYANG TECHNOLOGICAL UNIVERSITY NATIONAL INSTITUTE OF EDUCATION NIE SINGAPORE、UNIVERSITY OF TEXAS SYSTEM、ETH ZURICH、NATIONAL UNIVERSITY OF DEFENSE TECHNOLOGY CHINA、PEKING UNIVERSITY、UNIVERSITY COLLEGE LONDON、UNIVERSITY OF CHINESE ACADEMY OF SCIENCES CAS、CENTRE NATIONAL DE LA RECHERCHE SCIENTIFIQUE CNRS、PENNSYLVANIA COMMONWEALTH SYSTEM OF HIGHER EDUCATION PCSHE（百度翻译：中国科学院、北京邮电大学、伦敦大学、IBM、加利福尼亚大学系统、联邦科学工业研究组织、北航大学、巴黎大学、新南威尔士大学悉尼分校、康奈尔大学、南洋理工大学、南洋理工大学新加坡国立教育学院、得克萨斯大学、苏黎世联邦理工大学、中国国防科技大学、北京大学、伦敦大学学院、中科院大学、国家科学研究中心、宾夕法尼亚联邦高等教育体系。）

![visualization_机构.jpg](https://upload-images.jianshu.io/upload_images/637344-9577eba88c70369f.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)





#### 变量关系维度

**学科**

结合 web of science 自带的文献分析，从学科出现次数排列，区块链涉及了诸多学科，学科方向分别是:COMPUTER SCIENCE；ENGINEERING；TELECOMMUNICATIONS等诸多学科。

![visualization_研究方向.jpg](https://upload-images.jianshu.io/upload_images/637344-72579965d41cfc55.jpg?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

排名前 20 的学科如下：

![visualization_学科.png](https://upload-images.jianshu.io/upload_images/637344-7de9de8f69455bf3.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

再综合使用 citepace 科学计量工具对其进行分析，从学科分类上看，COMPUTER SCIENCE；COMPUTER SCIENCE, THEORY & METHODS；COMPUTER SCIENCE, INTERDISCIPLINARY APPLICATIONS（计算机科学；计算机科学、理论与方法；计算机科学、跨学科应用）具有突现性，说明这三个学科方向对区块链的发展有转折意义。

![Category.png](https://upload-images.jianshu.io/upload_images/637344-497bec6dba4744b7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**引用文献**

借助 citespace ，分析共被引文献，了解背后的知识基础，分析发现共有 35988 篇引用文献，通过突现分析，发现排名第一的是 NAKAMOTO S 最早于 2008 年发表的一篇名为 BITCOIN PEER TO PEER 的文章，这篇文章对该领域有重大影响，是区块链学术领域的奠基之作。

![Burst](https://upload-images.jianshu.io/upload_images/637344-a3bc7ab6a82e10ab.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**关键词知识图谱**

**关键词**

对下载的文献关键词进行分析，通过词频统计可以发现学术研究最热门的话题，筛选出区块链在行业应用领域频次>=10的关键词：

![Fre>=10](https://upload-images.jianshu.io/upload_images/637344-575d766d6c2a94eb.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

1、金融：比特币、数字加密货币、以太坊、数字货币、金融科技是高频词，这意味着金融是区块链行业应用领域的研究热点；
2、物联网：iot、internet of thing均表示物联网，且是高频词汇，这意味着物联网是区块链行业应用领域的研究热点；
3、溯源：供应链是高频词汇，这意味着供应链是区块链行业应用领域的研究热点；
4、其他：智慧城市、智能电网、医疗保健、微电网均是高频词汇，说明其是区块链行业应用领域的研究热点。

**突现词分析**

从突现上看，突现词分别为bitcoin、cryptocurrency、digital currency（比特币，加密货币，数字货币），表明比特币、加密货币、数字货币在一段时期内是行业研究的前沿。

![Burst](https://upload-images.jianshu.io/upload_images/637344-be312b5598edf5c8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**为防止遗漏，在此处附上所有词频，便于筛选**

![image.png](https://upload-images.jianshu.io/upload_images/637344-44b50a5037aac869.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![英文文献词频](https://upload-images.jianshu.io/upload_images/637344-f6db4c1f8390cf14.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## ChangeLog
- 201904032350 增删
- 201904021344 增删
- 201904012342 增删
- 201904011349 增删
- 201903301911 增删
- 201903300913 创建

**Comment by livingworld** [comment]
# 20190402 第二次小组会议纪要

## 摘要

参会人员：刘宇旸，王赓劼，朱婧，钟蓉，hetao，leon轩，舟舟，火冰

内容要点：

- 1.王赓劼同学做了自我介绍并给出了一些建议；
- 2.hetao同学分享下citespace的调查结果；
- 3.leon轩阐述了区块链领域在政策变动下，亟待形成一套评判区块链公司好坏的标准局面。
- 4.组长分享了国内政策关于区块链行业的基调，并谈到接下来探索的方向；
- 5.组员确定好各自任务。

### 探索问题

- 1.中国政策是支持有token还是无token区块链？
    + 组长：根据2018年中国银行发布的区块链领域的相关文件，指明了对和货币相关的项目不做支持，意味着重点还是支持无 token 的区块链。
    + 结论：
- 2.有币和无币的？
    + 组长：2018年中国银行发布了区块链领域的相关文件，把货币发在区块链上去流通在政策上不受支持，未来对区块链的支持，更多的会体现在行业领域应用上，即把区块链当做一种科技落地的设施，同时不可避免会引入中心化的成分。
    + 王同学：中国银行的文件划了一条红线，即区块链里面的代币不要和法定货币产生联系，不能去换。
- 3.行业区块链应用是属于有token的还是无token的？
    +  王同学：中国银行的文件只是划了一条红线，不要碰货币相关的。跟区块链到底有没有 token ，可能没有刚性的关系。token 它在比特币里面就是等于比特币，就是工作量占比。从李笑来的 pressone项目上看，还是需要一个激励机制来证明对网站建设的工作量，还是需要有一些东西去度量。现目前，我们不需要纠结是有 token 还是无 token 的，应该将视野稍微放宽点。
- 4.行业区块链应用真正做的“实事”是什么？
    + 待进一步探索。
- 5.都有哪些真正做“实事”的公司？
    + 待进一步探索。
- 6.10年后区块链行业可能会是什么样？
    + 待进一步探索。

## 相关建议

- 刘宇旸：
    + 1.工信部发布的研究报告。2016年和2018年发过两次。他在2016年的报告在工信部网站上已经删除了。对比了两个报告，发展路径。
        * 技术比较：现在完全不提区块链1.0、区块链2.0的说法了。现在开始提安全、跨链等技术方面的内容了。后面可以考虑，是否要结合技术这块来讲。
        * 典型应用场景比较：已经做了一些缩减，国家对区块链的技术已经缩减到非常小的领域了，2018年主要集中在金融、供应链、智慧城市、公共服务、治理等方面。先前提到的有些领域的应用已经不提了。
        * 基础设施：结合实际的场业进行.....
        * 可以搜集一下编写相关报告或白皮书的机构有哪些，可以找过来分析一下。
    + 2.一个反常识的点，可以找找看，有哪些风投公司为什么不跟进国家政策，还往跟货币相关的区块链领域投资。

- 王赓劼：
    + 1.关于找到闷声发大财的公司。除了从区块链在其他行业应用领域的角度来看，还可以思考，有哪些做比特币发大财的公司，这些赚钱的公司都有什么样的特点等等；
    + 2.将视野放宽一些，不要急着收敛。可以在本周内，将素材和资料收集好，周末碰头后确定 bp输出目标，下周做 bp；
    + 3.先从风头公司入手，做个列表，结合研报的共同点，作为我们未来行业控制指数的维度。

- Leon轩:
    + 区块链备案号：前两三天，所有北京区块链备案已经下来了。中国工信部出了一个备案的提案，现在已经出来了。此前这个行业一直属于灰色地带，现在备案了，是一个非常重要的改革点。法律已经跟上来了，形势已经变了，这个节点之后，去告诉它们，怎么去合规，具有重大的意义。
    + 好的评价机制有待建立：随着区块链行业监管将强，实施备案，原有衡量区块链项目或公司好坏的维度、评价指标已经变了，现在迫切需要提供一个新的指标评价体系来评判一个项目。衡量项目的好坏的维度变了。由于这个行业有大量的研究报告，全局认识每时每刻都在变化，再去做一个报告，和之前它们的研究报告又有什么差异。所以，找到一个新的框架。不要再自己重复造轮子了。用信分课程的内容直接参考别人的研究成果，提出一个新的评价标准是更好的思路。

- hetao：
    + 国内文献：根据分析的情况，国内关于区块链的热点研究主要集中在金融领域，其次是物联网、供应链、共享经济、能源互联网等领域，此外，比特币、金融、银行业、财政金融、数字货币、互联网金融等方面研究在一段时期内是行业研究的前沿。
    + 国际文献：根据分析的情况，国际文献中关于区块链的热点研究同样主要集中在金融领域，其次是物联网、供应链、智慧城市、智能电网、医疗保健、微电网等领域。比特币、加密货币、数字货币等方面研究在一段时期内是行业研究的前沿。

## 会议结论

- 1. 基于对政策的调研，确定BP的研究范围是区块链行业应用，不涉及炒币、数字货币等。
     + 2017年9月4日 央行联合网信办等机构，将ICO定性为非法集资并全面叫停。
     + 2018年 央行 第4号文件 [区块链能做什么、不能做什么？](http://www.pbc.gov.cn//yanjiuju/124427/133100/3487653/3658001/index.html)明确表示：区块链无法有效履行货币职能、公开发行交易的Token 的项目违法行为普遍、区块链落地时需要可信任的中心化机构。
     + 2019年 3月30日 国家网信办官网发布第一批境内区块链信息服务备案编号，对区块链企业监管进一步落实。

- 2. 缩小了区块链行业应用的行业范围，到物联网、供应链、智能电网、智慧城市、微电网、法律等领域。
    + 从web-of-science的数据分析结论来看，国际上对区块链在行业应用方面的主要集中在上述几个领域。

- 3. 通过对区块链行业应用企业的公司的多维度分析，尝试得出如下结论：
   1. 基础：有哪些代表性的公司，他们的价值在哪里？
   2. 进阶：对区块链行业的公司给出一个价值评估体系。

## 后续问题

各位同学使用信分课中商业分析部分给出的方法，各自从不同的角度来选取和分析公司，尝试从全局认识，有趣度，反常识多种角度来思考。有以下几个思路可供选择：
1. 基础：
    - 1）.第一批境内区块链信息服务备案的公司；
    - 2）.找到白皮书中提到的公司；
    - 2）.找到国内区块链风投排名及选择的投资公司；
    - 3）.找到国际区块链风投排名及选择的投资公司；
    - 4）.从专利分析区块链技术的应用及各公司的发展方向。

2. 进阶：
    - 1）.原来炒币的公司有哪些是赚签订，为什么赚钱？
    - 2）.现在的区块链公司的评价维度是什么？如何建立新的评价标准？

大家选择自己感兴趣的方向认领吧，列表中没有的也可以补充上。

商业信息分析方面，课程组建议可以总结成三张表：1. 区块链行业的重要公司，2. 公司的股东关系，3. 销售利润情况。

大家如果总结出一些表格数据之类的就及时发在群里或者跟帖，互通信息。

## ChangeLog
- 201904031308 增补刘宇旸会议纪要
- 201904022300 hetao 创建

**Comment by livingworld** [comment]
## 区块链学术领域的分析

### 数据源

**国内文献**

在中国知网上以 `区块链` 为关键词检索期刊学术信息，国内该领域的研究正处于蓬勃发展的状态，近几年的年发文量超过千篇，但发文质量参差不齐，充斥着大量非文献相关的文章，由于只需要对可靠文献进行分析，获取国内区块链学术领域研究热点。因此，在此次分析研究中，仅选择硕博学位论文和SCI来源期刊、EI期刊、核心期刊、CSSCI期刊、CSCD期刊，结合人工筛选，截止2019年3月31日，共得到1019篇学术文献，对文献进行分析，样本文献时间区间为 2014至2019年。

**国际文献**

在 web of science 平台上，以 web of science 核心文献为数据源，检索 `blockchain` 主题词，截止2019年3月31日，共得到 1942 篇学术文献，对文献进行分析，样本文献时间区间为 2013至2019年。

### 时间分布

![文献时间分布图](https://upload-images.jianshu.io/upload_images/637344-1cf58f5c29600c89.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

从时间上看，国内于2016年起开始快速增长，并以成倍的速度增长。

从时间上看，国际上关于区块链的学术研究于 2016 年起开始快速增长，并以成倍的速度增长，这与国内的文献相吻合。

### 热点研究领域

关键词知识图谱能将区块链领域的学术研究热点较好展示出来，基于 citespace 软件提取高频词汇，在 citespace 中，研究热点一般用频次（Frequency）来体现。如图所示，分别是国内外区块链研究领域出现频次不小10的关键词图谱，为排除 `blockchain` 或 `区块链` 这一高频词的干扰，均已进行过滤：

![国内文献Freq>=10的关键词.png4](https://upload-images.jianshu.io/upload_images/637344-23a5f21c490c6068.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


![国际文献Fre>=10的关键词.png](https://upload-images.jianshu.io/upload_images/637344-4d47c8dd7f3afc76.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

进一步筛选出国内外学术研究领域与区块链应用相关的高频词汇，如图为出现频次不小于10的词：

![国内文献.png](https://upload-images.jianshu.io/upload_images/637344-dc1b0994c2f86779.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![国际文献.png](https://upload-images.jianshu.io/upload_images/637344-853003b3b2b8f843.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**国内文献研究热点**

区块链技术在行业应用方面的学术研究，主要分为以下几大类：

1、数字货币：比特币（91）、数字货币（55）、数字货币（10）是高频词，能反映区块链技术在数字货币领域的应用是研究热点；
2、金融：金融科技（31）、互联网金融（26）、金融（25）、财政金融（21）、金融机构（16）、银行（16）、供应链金融（15）、金融创新（12）、银行业（12）、监管科技（11）、商业银行（10）是高频词，能反映区块链技术在金融行业领域的应用是研究热点；
3、物联网：物联网（19）是高频词，反映区块链在物联网行业领域的应用是研究热点；
4、供应链：供应链金融（15）、供应链（10）是高频词，反映区块链技术在供应链领域的应用是研究热点；
5、能源互联网：能源互联网（16）是高频词，反映区块链技术在能源互联网领域的应用是研究热点；
6、共享经济：共享经济（10）是高频词，反映区块链技术在共享经济领域的应用是研究热点。

**国际文献研究热点**

区块链技术在行业应用方面的学术研究，主要分为以下几大类：

1、数字货币：比特币（245）、数字加密货币（109）、数字货币（23）是高频词汇，反映区块链技术在数字货币领域的应用是研究热点；
2、物联网（149）：物联网是高频词汇，反映区块链技术在物联网领域的应用是研究热点；
3、智慧城市（26）是高频词汇，反映区块链技术在智慧城市领域的应用是研究热点；
4、供应链：供应链（25）是高频词汇，反映区块链技术在供应链领域的应用是研究热点；
5、能源电力：智能电网（23）、微电网（15）均是高频词汇，反映区块链技术在能源电力领域的应用是研究热点；
6、金融：金融科技（20）是高频词，反映区块链技术在金融领域的应用是研究热点；
7、医疗保健（16）是高频词汇，反映区块链技术医疗保健领域的应用是研究热点。

### 小结

区块链技术在数字货币、金融、物联网、供应链、能源领域的应用研究均是国内外的热点学术研究领域。其中，数字货币领域的研究都是国内外最最热门的话题；金融领域，都有聚焦的小领域，但中文文献的研究热度和要广度明显高于外文文献；物联网领域，外文文献的热度明显高于中文文献文献；供应链领域，在中文文献和外文文献排名都比较靠前，国内文献中供应链与金融关联度较高；能源领域，国内文献的研究主要集中在能源互联网方面，涉及面较广，而外文文献聚焦在电力行业。

## 前沿研究领域

基于 citespace 软件的突现词（Burst）分析功能，可以发现区块链学术研究领域的前沿研究领域。突现词分析功是按照时间顺序排序的突现词演变，表明某一时段突然上升或突然下降的节点，这类节点能代表某一个时段的研究前沿。

### 国内文献

![国内文献 Burst 图](https://upload-images.jianshu.io/upload_images/637344-1d746e41f8bf9750.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

突现词分别是比特币、金融、银行业、财政金融、数字货币、互联网金融，反映出区块链技术在这些方面应用的学术研究在一段时期内是研究的前沿。

### 国际文献

![国际文献Burst图](https://upload-images.jianshu.io/upload_images/637344-be312b5598edf5c8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

突现词分别为bitcoin（比特币）、cryptocurrency（加密货币）、digital currency（数字货币），反映出区块链技术在这些方面应用的学术研究在一段时期内是研究的前沿。

### 小结

中文文献和外文文献研究中，数字货币都一度成为一段时期的前沿研究，此外，中文文献中区块链技术在金融领域的应用研究较为突出，区块链技术在其他行业领域应用的前沿研究尚未显现。

## ChangeLog
- 20190411
