### ISSUE TITLE
第三次小组会议 20190407

### ISSUE THREAD

**Issue by happylyy** [livingworld/IA004_blockchain#5]
会议记录：朱婧
会议日程：
1. 组员分享上次认领任务的探索结论。分享内容包括以下几个方面:
    - 上次认领任务
    - 探索思路，探索问题
    - 结论
    - 反常识点或者有趣点
2. 根据本次大家的结论，拟定BP的结论，输出大纲。
    - 输出大纲
    - 认领任务，分头输出

**Comment by jingzom** [comment]
## 20190407第三次小组会议记录

## 摘要

参加人员：刘宇旸，王赓劼，朱婧，钟蓉，hetao，花儿笑，舟舟

内容要点：

1.组员分享上次认领任务的探索结论。分享内容包括以下几个方面:

- 上次认领任务
- 探索思路，探索问题
- 结论
- 反常识点或者有趣点

2.根据本次大家的结论，拟定BP的结论，输出大纲。

- 输出大纲
- 认领任务，分头输出

## 探索内容

一、刘宇旸：主要数据及内容见https://github.com/livingworld/IA004_blockchain/issues/4

1. 从风投公司入手研究区块链公司，找出有价值的行业区块链公司。

   结论：风投比较青睐于社交、娱乐、金融行业。

   有趣点：跟我们前期得到的结论是不太契合的

   2.在行业公司里进行区块链的对比

   3.从风投投资的角度和国家公示的区块链的公司是不是一样的？是不是合规的公司？

   4.风投公司认为这些公司好在哪里？待继续。

   总结论：风投领域与技术分析公司不一样，更注重供应链、物联网等，也是更成熟的方向。其他领域更加新兴，还在前期阶段。

   二、朱婧：主要内容见https://github.com/livingworld/IA004_blockchain/issues/4

   1.通过专利申请人发现4家重点公司

   相关情况待后续继续深挖

三、hetao

1.万向公司

2.分布信息科技有限公司

四、钟蓉

1.众安

2.

五、王庚劼

研究了两家公司

得出结论：区块链解决信任的问题

区块链落在IOT和供应链上的应用

刘宇旸：前20名风投的公司投资的唯链，MItech……根据溯源公司的案例，看国内怎么做的

## 后续行动

选到几个靠谱的公司，再深挖一下，数据支撑是否能支撑王同学的结论？

需要列出公司list

Action1:找靠谱的公司

Action2:公司再深挖一下数据



## 疑问点

1.舟舟教练提问：投资事件的数量，重要的私募基金比较靠前的是娱乐为主的几大项，跟学术上的探索有出入。这个数量的话只看的是数字还是把pre-A和A轮是同一对待的？担心会有遗漏

2.花儿笑教练：BP呈现需要哪些信息点？要重点关注

## ChangeLog

- 20190407 朱婧创建

**Comment by happylyy** [comment]
## 20190407第三次小组会议记录



## 摘要 

参加人员：刘宇旸，王赓劼，朱婧，钟蓉，hetao，花儿笑，舟舟

内容要点:

1. 组员分享上次认领任务的探索结论。
2. 根据同学们的探索结果，将BP呈现的信息收敛如下：
   1. 回顾比特币和区块链技术的历史，看到区块链的出现是为了解决数据中心化而导致的信任危机。10年时间，比特币的野蛮生长滋生了了众多围绕比特币、ICO概念进行炒作的公司圈钱，从而各国政府已经对区块链进行不同层面的监管。
   2. 通过对区块链风投公司、区块链创新50强公司、国内BAT的布局等数据的调查，抛开炒币、ICO这些概念炒作，区块链在实体经济的落地比较可行的场景是IoT+供应链。
   3. 如何判断区块链在IoT+供应链落地的公司是否有价值，是否靠谱？有哪些判断标准？
3. 后续安排：
   1. 钟蓉负责构思BP呈现方式
   2. 其他同学针对BP大纲的第三点继续深挖，通过对多家区块链在IoT+供应链应用项目的总结，对判断一家区块链公司是否靠谱的标准进行优化。



## 重点内容

1. 刘宇旸：主要数据及内容见[#4](https://github.com/livingworld/IA004_blockchain/issues/4)

   1. 从风投公司入手研究区块链公司，找出有价值的行业区块链公司。列出区块链行业排名前20的风投公司的所有项目，筛选和数据调整后根据行业进行统计。分析如下：

      - 投资事件发生较高的行业是社交、娱乐、金融行业。
      - 被多家（3家及以上）风投关注的公司集中在文化，社交，娱乐，营销，供应链，金融，共享经济领域。
      - 区块链应用领域，进入A轮及以后的公司有三家，均属于供应链行业。

      结论：结合“中欧世界前50强研报”中行业应用领域估值最高两家公司分别从事物联网和供应链溯源行业来看，风投青睐的公司中，供应链领域更加成熟，其他文娱、社交等领域还在兴起阶段一般都是战略投资或者天使轮。

   2. 在风投圈的公司中查找是否与政府公司备案名单中有重合的公司（合规角度），发现了四家公司。

      - 万向区块链（投资公司）：投资了多家公司，分布在金融、文化、共享经济等行业。其中Nervos是企业区块链解决方案提供商。

      - 唯链（供应链）：由千方基金和分布式资本投资，现在Pre-A轮，是区块链供应链管理服务商。

      - 布比区块链（金融）：分布式资本投资两轮，现在已经到A轮，是区块链金融科技技术提供商。

      - 分布科技（金融）：区块链金融科技服务商，原小蚁NEO的CEO创办，从商业评论上来说有上家公司有套利割韭菜的嫌疑，口碑不是太好。

2. 朱婧：主要内容见[#4](https://github.com/livingworld/IA004_blockchain/issues/4)

   1.通过专利申请人发现4家重点公司

3. hetao：深入挖掘了两家公司，上海万向区块链股份有限公司和上海分布信息科技有限公司来分析

   这两家公司都是跟进政府政策，并且在风投圈也比较活跃。

   - 上海万向区块链股份有限公司：产业非常庞大，是国内进入区块链行业比较早的公司之一，主要从事底层技术，也提供企业级服务。
   - 上海分布信息科技有限公司来分析：主要从事区块链金融方向的业务，也有部分区块链底层技术。

4. 钟蓉：深入挖掘了两家公司，众安信息技术服务有限公司、深圳前海微众银行股份有限公司

   - 众安信息技术服务有限公司，推出了一个步步鸡项目，作为区块链产业布局的试点。
   - 深圳前海微众银行股份有限公司，腾讯控股的银行公司，区块链只是其产业中的一部分。

   以上两家公司在区块链技术方面的研究都不是很深入，现有资料来看是希望通过对区块链技术的探索，将其应用在公司自身的金融领域。

5. 王庚劼：研究了两家国外的公司，Skuchain和Dfinity。

   - Skuchain：利用区块链智能合约，跟踪合同执行和管理。利用区块链防篡改、易跟踪，跟踪特殊商品销售使用。
   - Dfinity：研究第三代区块链底层技术，着眼点在于提高交易速度和解决区块链平台法制规范问题。

   结论：

   1. 区块链+IOT是现阶段的趋势热点
   2. 底层技术需要突破，看好真正有技术壁垒的公司（这个不在本次BP研究范围，不继续深挖）
   3. 判断区块链公司是否靠谱的标准：不涉及协作的区块链都是忽悠；如果没有区块链，是否可以解决业务问题？；区块链实施费用高昂，上链场景是否能支撑其上链费用？

6. 结合王同学的结论和“中欧世界前50强研报”给出的区块链项目评价标准，给出判断区块链公司是否靠谱的初步标准：

   1. 区块链落地场景是否涉及协作；
   2. 上链的实体价值是否能超过上链后高昂的计算费用；
   3. 如果没有区块链技术，该场景是否依旧可以落地；
   4. 创新力：从共识机制创新、加密算法创新、性能和安全、生态创新几个角度是否有突破；
   5. 团队：团队的技术背景，以及过往经历是否可以支持对业务场景的深入理解。



## 后续行动

Action1:钟蓉负责构思BP呈现方式

其他同学针对BP大纲的第三点继续深挖，通过对多家区块链在IoT+供应链应用项目的总结，对判断一家区块链公司是否靠谱的标准进行优化。同时也分析下BAT在IoT+供应链场景的落地情况，进行对比。
Action2：大家把今天分享的内容都传到github仓库，文件上传到reference文件夹，描述及结论在[issue 4#](https://github.com/livingworld/IA004_blockchain/issues/4)中跟帖。
Action3: 王赓劼、朱婧、刘宇旸根据现有材料提供几家在IoT+供应链应用的项目，供深挖。

Action4: 各自认领1-2家深挖的公司，根据现在已经总结出来的评价标准进行验证。不符合标准，又认为有价值的公司，要继续深挖其特点。

下次讨论：20190410，周三晚上7点半


## 疑问点

1.舟舟教练提问：投资事件的数量，重要的私募基金比较靠前的是娱乐为主的几大项，跟学术上的探索有出入。这个数量的话只看的是数字还是把pre-A和A轮是同一对待的？担心会有遗漏



## ChangeLog

- 20190407 朱婧创建
- 20190407 刘宇旸补充



## 参考资料

详情请参考[阳志平：专业主义，从备忘录开始](https://mp.weixin.qq.com/s?__biz=MzA4ODM4ODQ3MQ==&mid=2651937363&idx=1&sn=97f6f2b8d593055f064b07e5578f47fa&chksm=8bcf1c4bbcb8955d32686b1191b66d6f0f2b0e774691ccc92fbcd2a3ecb73cf824ccf37a03b4&scene=7&ascene=0&devicetype=android-28&version=2700033b&nettype=WIFI&abtest_cookie=AwABAAoACwATAAQAI5ceAFaZHgDBmR4A3JkeAAAA&lang=zh_CN&pass_ticket=5YcaMOPlJiUS2PaPDjhTwTdepF1F4yY0uKlSWu5sv9DPuHF%2F%2BihYO5p59feMDwAE&wx_header=1)
