### ISSUE TITLE
BP路演呈现方式

### ISSUE THREAD

**Issue by happylyy** [livingworld/IA004_blockchain#6]
本帖专门用于讨论最后路演时如何呈现。从有趣和反常识切入，以故事为线索。
有思路就在下面跟帖就好

**Comment by happylyy** [comment]
先写个王同学的点子：
区块链投资防骗指南

**Comment by happylyy** [comment]
我的想法：
（借鉴了上期思思同学的bp思路）
从一个投资比特币尝到甜头的小白入手，买了比特币之后发现区块链市场很大，打算继续投资，该怎么办？
可以有两个小白，一个研究行业区块领域，给出区块链投资防骗指南；另外一个继续炒币，由于政策缘故到了一批交易所，未来比较茫然。

**Comment by fishwgj** [comment]
逻辑上存在问题。
1. 区块链（非炒币）公司目前鲜有在普通人能接触的二级市场上市。
2. 一个居然尝到比特币甜头的小白，大概率继续炒币

**Comment by szmozh** [comment]
- 分行业赛道呈现各行业的代表公司及其项目，哪些项目是闷声发财的，哪些项目实施对生活带来的改变，或者预测一下公司是否会成为下一个独角兽。
