### ISSUE TITLE
深挖供应链+Iot行业中的区块链项目

### ISSUE THREAD

**Issue by happylyy** [livingworld/IA004_blockchain#7]
根据周日的讨论：现阶段的进展是将区块链行业应用聚焦在物联网+供应链这个领域，认为在这个领域落地比较有价值和实际意义。结合王同学的结论和“中欧世界前50强研报”给出的区块链项目评价标准，给出判断区块链公司是否靠谱的初步标准：（其他同学还有的话可以补充）
1. 区块链落地场景是否涉及协作；
2. 上链的实体价值是否能超过上链后高昂的计算费用；
3. 如果没有区块链技术，该场景是否依旧可以落地；
4. 创新力：从共识机制创新、加密算法创新、性能和安全、生态创新几个角度是否有突破；
5. 团队：团队的技术背景，以及过往经历是否可以支持对业务场景的深入理解。

后续，每位同学选择1-2个项目/公司进行分析，来验证上述区块链项目的评价指标是否可行。（推荐选两个，创业公司一个，国内BAT或者前期已经初步调查的公司选一个进行对比，正反面的案例都看一下）

**Comment by livingworld** [comment]
认领：
漂流链Plcchain、食物优

1.食物优的投资方之一是分布式资本，分布式资本法人代表肖风同时也是万向区块链法人代表。
2.在比较明确的食物供应链上，想要了解其实际落地效果。

**Comment by happylyy** [comment]
补充下，大家选项目的时候先给出个假设，做一下初步调查，给出个选择的理由。然后以最短的时间对公司做个最最小的全局认识，对公司分析的时候如果假设被推翻了就换一家公司，迅速试错。周三的时候，每个人都要给出一个明确的分析结果。

**Comment by happylyy** [comment]
我选了MXC和唯链，它们两个都是分布式资本投的，上周老王分析skuchain分布式资本也投了，希望通过横向对比看下这三家公司的共同特点。

**Comment by happylyy** [comment]
我今天看到了一个链塔出的区块链溯源产业报告，里面讲的听清楚，回头可以写个溯源行业的最小全局认识。里面国内BAT和唯链，skuchain，溯源链都提到了。
之前风投列表里面还剩下MXC，Mitech以及中欧50强里面的IOTA没有看到相关的信息。

**Comment by livingworld** [comment]
## 公司网络

![关联图谱图](https://upload-images.jianshu.io/upload_images/637344-2c94212d7fb840e4.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![股权穿透图](https://upload-images.jianshu.io/upload_images/637344-bf3a59fec6a5daee.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![企业图谱](https://upload-images.jianshu.io/upload_images/637344-fd0c54b6f1fd9182.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

公司规模小，是一家初创公司，创始人还有一家小规模的快递公司。

## 公司简介

1.公司介绍：上海铭勇信息科技有限公司成立于2016年11月16日，是一家有限责任公司（自然人投资或控股），法定代表人王需勇，属于信息传输、软件和信息技术服务业的一家公司，公司最终受益人王需勇。

2.漂流链app：企查查介绍情况：
>王需勇创立的漂流链App，是基于区块链技术的物流链，在这个链上人人都是快递员，将出行的闲置空间与社会共享，可以提高行业效率、降低成本、产生新的社交关系，并能够国际化；同时，基于区块链的不可篡改性还根本上解决快递员贩卖用户信息和包裹丢失及配送过程中责权扯皮问题。基于上述，漂流链主要搭建一个基于区块链的物流数字社区平台，初期在平台发行Token PLC（PIAOLIUCOIN），即漂流币，漂流币也是平台唯一的流通媒介。漂流币代表了漂流链数据的使用权也代表了所有权，使用漂流链数据或漂流链上的应用需要支付一定的漂流币，体现使用权。产品层面，漂流链是一款平台App，一方面可以使用参与行业的ICO，另一方面可以在系统中直接寄快递、查物流信息、共享物流环节赚取漂流币。具体到使用场景，用户在平台下单后，用户的快递对应一个唯一的密钥（根据平台隐私规则，密钥包含地点、收件人、联系方式等信息），根据规则设定漂流币的数量，然后平台其他用户可以接单，并按照唯一密钥配送至收件人，收件人根据密钥取件并确认收件，配送完成后漂流币转至快递员账户。

一一分解：

>王需勇创立的漂流链App，是基于区块链技术的物流链，在这个链上人人都是快递员，将出行的闲置空间与社会共享，可以提高行业效率、降低成本、产生新的社交关系，并能够国际化；

理解：1. 没有找到这个漂流链app；2.人人都是快递员...这也太夸张了吧；3.这样的社交关系是创造了什么价值吗？还国际化？......

>同时，基于区块链的不可篡改性还根本上解决快递员贩卖用户信息和包裹丢失及配送过程中责权扯皮问题。

理解：1.这些问题，不需要区块链也能解决；2.发货方、寄货方、收件方都使用要使用这款产品才能实现？看着不靠谱。

>基于上述，漂流链主要搭建一个基于区块链的物流数字社区平台，初期在平台发行Token PLC（PIAOLIUCOIN），即漂流币，漂流币也是平台唯一的流通媒介。漂流币代表了漂流链数据的使用权也代表了所有权，使用漂流链数据或漂流链上的应用需要支付一定的漂流币，体现使用权。

理解：看上去是发数字货币的，炒币的。顺路找了下[漂流币-区块链闪电网络技术平台](http://www.piaoliubi.cn/)，这个网站看上去就不靠谱。

>产品层面，漂流链是一款平台App，一方面可以使用参与行业的ICO，另一方面可以在系统中直接寄快递、查物流信息、共享物流环节赚取漂流币。具体到使用场景，用户在平台下单后，用户的快递对应一个唯一的密钥（根据平台隐私规则，密钥包含地点、收件人、联系方式等信息），根据规则设定漂流币的数量，然后平台其他用户可以接单，并按照唯一密钥配送至收件人，收件人根据密钥取件并确认收件，配送完成后漂流币转至快递员账户。

理解：1.邮递什么快递也没有讲...只讲是做物流的...可操作性太弱了....

3.核心成员介绍：

王伟：其查查上介绍，王伟，连续创业者，从事物流共享事业3年，曾创立一家电商代运营平台公司，并以近千万的价格成功出售给国内知名小家电品牌公司。

王需勇：担任4家公司法人，分别是上海铭勇信息科技有限公司、空间客车(上海)信息科技有限公司、上海麦涛信息科技有限公司、濂溪区需勇综合商店店（继续深挖这几家公司背景。）	，漂流链Plcchain创始人，10年互联网连续创业经验，4年快递行业从业经验，热衷并信仰于区块链和数字货币研究，先后创立三个移动互联网品牌外卖网络、团购网站、空间客车，两次获得中国第一天使投资人薛蛮子投资。

![王需勇](https://upload-images.jianshu.io/upload_images/637344-f2cb6f2ac7afab3b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

陈虎：漂流链Plcchain联合创始人，20年快递从业经验，行业科班出身，专业性全国排名前五，前后担任顺丰和百世汇通快递高管职位。

Tom Xiao，漂流链Plcchain联合创始人，MatLab专家，主持过多项大型商业软件系统的开发。

4.公司人员：企查查上没有公司人员情况，没有查找到参保人数，可疑。

5.企业业务：漂流链Plcchain，2017年9月日获得薛蛮子天使轮投资，此后没再融资过。

6.知识产权：没有注册商标和专利申请，只有一家打不开的[www.plcchain.com](http://www.plcchain.com/)网站。

6.舆情：企查查上查找该公司的舆论报道，最新一期是2018年2月[漂流链：打造全新物流数字社区平台，充分保证信息安全|新芽链库_新闻_新芽NewSeed](https://news.newseed.cn/p/1343330)，此后该公司处于沉寂状态。

7.企业信用决策报告：根据企查查《企业信用决策报告》，该公司综合评级B，85分。

8.优势：无论是创新力、团队、还是落地场景，没有发现什么特殊的优势。

9.对外投资：无对外投资。

10.公司创始人背景：

王需勇控股的上海麦涛信息科技有限公司于2018年03月02日被税务部门行政处罚过，出现在了企业失信名单上 [权威发布:金山法院公布最新一批失信名单,金山24家涉“双欠”企业名单向社会公布-企查查](https://www.qichacha.com/postnews_8d3650c7149349eb92909c5144f7d9d0.html)；空间客车(上海)信息科技有限公司经营异常1次，行政处罚2次。

## 结论

从以下维度来评判上述信息：

- 区块链落地场景是否涉及协作?

涉及了协作，但这种协作无疑大幅度提升了成本呀，而且可操作性太弱了，这得运输啥。

- 上链的实体价值是否能超过上链后高昂的计算费用?

上链后成本会是非常高昂的，初创公司涉足这样的领域，前途几何？

- 如果没有区块链技术，该场景是否依旧可以落地?

该产品所提倡的场景过于宽泛了，没有实指~更像是一个概念~

- 创新力：从共识机制创新、加密算法创新、性能和安全、生态创新几个角度是否有突破?

创新力：完全没有体现出创新力在哪里，专利技术和商标没有，落地的服务也没见，技术上的支撑也没见。

- 团队：团队的技术背景，以及过往经历是否可以支持对业务场景的深入理解?

团队：主要的核心成员都是快递物流行业出身，另有一家小型快递公司，公司创始人控股的多家公司有多次失信记录，不太靠谱。

## ChangeLog
- 201904082340

**Comment by livingworld** [comment]
## 公司网络

![关联图谱.png](https://upload-images.jianshu.io/upload_images/637344-aa7a7a7c296705be.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![企业图谱](https://upload-images.jianshu.io/upload_images/637344-d661cbc30df07084.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![股权穿透图](https://upload-images.jianshu.io/upload_images/637344-00a2d2f61d6e43f0.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![image.png](https://upload-images.jianshu.io/upload_images/637344-a7f8f156333d966c.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

从图谱上可以发现， 食物优产品所在的公司股东有来自 “万向系” 的投资，SHEN BO 作为董事参与到其中。符安文是公司实际控制人。

## 公司简介

1.公司介绍

>成都埃克森尔科技有限公司作为独立的第三方科技公司，独立研发运营的项目食物优，全球安全农场直达，让每一口食材全程可追溯。对农场进行的数据检测，区块链全程追溯，农场智能管理应用系统，以及国际技术和国际权威认证体系，实现了高品质生态安全农场食材种植、管理、品质把控。自2015年到2016年9月已服务全球287家农场，遍布25家机构数据共享，获得世界17个国家农业技术和食品安全评级公司联盟认证。团队主创人员均来自于互联网软件行业，有着丰富的项目实战经验。成都埃克森尔科技有限公司成立于2014年12月，是一只年轻和国际化的实战团队。有来自法国、美国、日本不同文化背景的商业成员；具备五年以上ＩＴ移动信息开发的跨界工程师团队；我们有着研发与运营数款，月盈利千万级别流水的产品经验。埃克森尔诚邀年轻的行业精英加入我们，公司实行转正半年后的成员全体持股。只要你满怀创业梦想，有专业技能与超强的学习能力，埃克森尔欢迎你的加入！

![变更](https://upload-images.jianshu.io/upload_images/637344-a13d25f877d141be.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


疑问：14年12月经营范围变更，开始涉足农副产品。不过，一个做农场食品的公司，居然团队主创人员居然全部来自于互联网软件行业？

2.知识产权

2017年前，共申请了27项商标，包括食物优（曾被驳回，2015-01-30开始申请，2015-12-04申请成功）、基数栈、XCENER BLOCKCHAIN（2017-08-21申请）、无域（2017-08-21申请）、SCRY.INFO（2017-07-17申请）、全栈。2项软件著作权。分别Scry.Cashbox钱包应用软件（2018-12-05注册）、食物优有机农产品电商平台（2015-05-12注册）。2017年5月29日注册有一家名为无域[SCRY.INFO](https://home.scry.info/)的网站。

![image.png](https://upload-images.jianshu.io/upload_images/637344-77078877f281316d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


信息点：无域[SCRY.INFO](https://home.scry.info/)、基数栈、XCENER BLOCKCHAIN是什么？

3.股东信息

上海万链投资中心(有限合伙)于2017-05-25入股，分布式资本 SHEN BO 作物董事参与其中。

![image.png](https://upload-images.jianshu.io/upload_images/637344-ab6806cb6d4f378e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

4.主要成员

公司主要成员：SHEN BO、符安文、李雪薇、翁京 他关联 3 家公司、于淼。

5.公司成员

缴纳社保的人员仅2人。


6.产品网站

- 通过企查查找到食物优网站。可是无法访问：[食物优](http://http//www.5ufarm.com)

7.挑战：

- 公司规模：不明确；
- 朱要成员中未见有食物或者农业相关领域背景的成员；
- 缴纳社保的人员仅2人；
- 产品网站已不运行。

## 产品介绍

食物优是成都埃克森尔科技有限公司的一款产品。通过[蝉大师 ](https://chandashi.com/apps/androidsummary/appId/54603764.html)查找该应用产品，截止2019年4月9日，在汇总的各渠道安卓手机上总下载量241725。

![image.png](https://upload-images.jianshu.io/upload_images/637344-c74b00b27e650c1a.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

日下载量较低，半死不活的状态，日下载量0或者个位数，还会有异常值......

![近一年状态.png](https://upload-images.jianshu.io/upload_images/637344-6576edd4a42b7191.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![近半年状态.png](https://upload-images.jianshu.io/upload_images/637344-255a5744a27a9199.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)


## 融资过程

融资过程：曾于2017年6月29日获得分布式资本、芳晟基金数千万美元A轮融资，用用区块链技术解决农业供应链的“信任危机”。

根据[食物优Xcener,成都埃克森尔科技有限公司,基于真实数据的开源区块链底层协议 | IT桔子](https://www.itjuzi.com/company/33953)查询的结果，食物优是一个农产品电商平台，目前签约合作有139家CSA中小型农场（社区支持农业）。

疑问？怎么成了一家农产品电商平台了，不是区块链平台吗？哪里不对？

## 食物优历史发展

>符安文于2014年7月创办食物优。2017年年初，符安文启动SCRY.INFO开源计划。它接入整合并签名不同的行业数据形成基于区块链的数据智能合约协议层，对于数据验证的节点参与方进行数据源的签名认证，不同的开发者和公司可在SCRY.INFO协议上开发自己的区块链数据应用产品。

来源：[符安文(Eva Foo)——食物优 SCRY.INFO無域 CEO | Hi区块链](https://www.hibtc.org/7027.html)，

信息点：食物优秀起初是什么公司？SCRY.INFO又是做什么的。

2016年05月11日新闻报道[上线半年就有13000的订单的食物优，可实现农牧场产品3小时到家#创新中国2016# - 初创公司 - 创业邦](https://www.cyzone.cn/article/145576.html)

>2015年11月上线的食物优，是一个农产品电商平台，目前签约合作有超过230家CSA（社区支持农业）中小型农场，已有13000多的注册用户和下单。其中已获得了56%的季度增长，复购率达到了51%。食物优将优质的小农场的食材提供给终端消费者，通过预定模式，实现零仓储、零物流。并通过后台预算，消费者可从农场终端预定食物。

信息点：2015年11月上线的食物优是一家农产品电商平台，这时还没有提到区块链~

2016年08月11日新闻报道[食物优签约Rollink 欲追溯全球16个国家品质食材|界面新闻 · 快讯](https://www.jiemian.com/article/794406.html)

>据了解，食物优是一个独立的科技第三方，为消费者寻找和监督最安全优质的农场产品，同时为农场提供国际先进的科技种植和数据计算优化指导方案。食物优全球安全农场直达，致力于提供完全无激素、无农药、无抗生素的高品质安全农场食材直达到家服务。

信息点：这时还没有提到区块链~

2016年11月01日新闻报道[我做人这么辛苦，难道是为了吃残留重金属和农药的食物？ - 初创公司 - 创业邦](https://www.cyzone.cn/article/154713.html)：

>去年11月上线的食物优，是一个农产品电商平台，目前签约合作有超过287家CSA（社区支持农业）中小型农场，食物优通过关注CSA小型农场，将遍布在中国和海外的中小型高品质CSA农场的食材以预订模式配送到家，从上游推动物理指标农场数据监控，到下游提供给消费者各种单品类小型安全农场食材。目前食物优所有农场已经获得了国际第三方的认证，包括日本和欧盟的。

>食物优使用区块链技术来对农场生命轨迹进行记录

>食物优现正在寻找Pre-A轮融资，希望联手更多产业链上下游合作伙伴，在资源、资金合作上共赢发展。

信息点：开始提到区块链，正在寻找 A 轮融资。

2016年11月16日新闻报道[食物优：用区块链玩转大农业怎么做？](https://www.sohu.com/a/119086295_485557)

信息点：标题再次提到区块链，概念起来了。

2016年11月17日新闻报道来看[食物优：生鲜果蔬从农场直达餐桌，它是这么做的 | 创业 - 动点科技](https://cn.technode.com/post/2016-11-17/shiwuyou/)：

>“食物优”是一个B2C农产品交易平台兼大数据管理网络，消费者可以在上面查看农场的详细信息，购买到国内外农场的高品质食材，而且产品都是可溯源的

>比如一盒有机西红柿，消费者用手机扫描包装盒上的有机追溯码，即可查询到食材的有机证书编号、认证中心和获证企业。而这也是依赖于从源头开始的食物优溯源系统，通过与美国麻省理工大学、日本、以色列先进的农业技术合作，对上游农场监控数据的开源共享，构建农产品可追溯系统的数据标签和算法管理。

>该项目相关负责人在路演现场介绍：“食物优为优质上游农场食材搭建了与客户链接的平台，让成都人可以购买全球230余家CSA农场（社区支持农业）的优质食材。”

文章讲食物优是一家B2C农产品交易平台，通过对上游农场监控数据的开源共享，构建农产品可追溯系统的数据标签和算法管理。没有特别强调区块链这一概念。

2017年07月06日新闻报道[食物优获得数千万美元A轮融资](https://www.sohu.com/a/154992537_505790)，开始获得A轮融资，文章大量出现区块链等概念。

信息点：结合企查查信息，2017年05月25日实现A 轮融资，2017年06月29日继续融资。

## SCRY.INFO是什么？

试图从无域[SCRY.INFO](https://home.scry.info/)中找到一些信息，进去之后发现是英文网站，连中文信息都找不到。

![image.png](https://upload-images.jianshu.io/upload_images/637344-5675471dd0b93aa8.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![团队](https://upload-images.jianshu.io/upload_images/637344-a2c884e1a39cb74e.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**SCRY.INFO是什么？XcenerBlockchain是什么？**

2017-07-06新闻报道，[成都区块链企业“埃克森尔科技”获千万美元A轮融资](https://www.sohu.com/a/155032526_118792)

信息点：提到将在 8月份推出 SCRY.INFO，此时商标还没有申请下来，但已经开始谋划了

2017年07月14日新闻报道[区块链砖家: 还在关注预测App？已经Out了！Scry.info 开源数据协议层到来雪球](https://xueqiu.com/3649092667/88763557)

>7月10日，成都天府软件园入驻企业成都埃克森尔科技有限公司（以下简称埃克森尔科技）CEO符安文介绍到，基于区块链技术不可篡改这一特性，公司开发了为农场提供信息化软硬件解决方案的项目“食物优”，“农产品从上游农庄到交到客户手中的整个环节，所有信息均自动纪录且无法篡改，相当于给了农产品一个‘数字身份证’”。而在下个月，该公司核心技术团队发起的基于真实数据区块链化的“SCRY.INFO开源计划”将正式启动，并成为全球首个将真实数据区块链化的底层协议社区项目，并邀请了全球超过6个国家不同背景的顶级开发人员共同构建Scry.info的社区发展

信息点：基于区块链技术不可篡改这一特性，公司开发了为农场提供信息化软硬件解决方案的项目“食物优”，食物优这款产品不是2015年12月上线的一家农产品电商平台吗？那是还没有区块链这个概念.....紧接着引出了 “SCRY.INFO开源计划”......

![image.png](https://upload-images.jianshu.io/upload_images/637344-4e472af03eec4837.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

2017年07月17日SCRY.INFO商标申请下来了，紧接着，2017年07月31日开始发布 [Scry.info白皮书前言+使命](https://www.sohu.com/a/161122733_99970957?sec=wd&spm=smpc.author.fd-d.5.1554823056565cVev6a0)。

随后，2017-08-05新闻报道[区块链智能合约引擎Scry.info完成国际PreICO](https://www.sohu.com/a/162443254_684500)

信息点：在新加坡完成国际PreICO私募阶段。

2017年8月18日，开始在 github 上新建 scryinfo 仓库，

github 仓库上，[Eva000001/scryinfo: The scry.info system base.](https://github.com/Eva000001/scryinfo) github上的仓库，最近一次更新还是两年前，代码关注度底，看上去是简单的 js 代码。

2017年08月25日新闻报道，[Xcener: 它用区块链服务农产品供应，还完成了 Pre ICO | 创业](http://www.sohu.com/a/167135467_485557)：

信息点："使用区块链技术追踪信息会更加可靠，因此这家公司开发了 Xcener Blockchain，向 17 个国家的品牌商、农场、国际跨国集团提供服务，产品涵盖 900 多家农场。" 还没有开发这项技术，就已经通过电商平台的形式向外服务了。

非小号上[DDD行情_Scry (DDD) 最新价格,历史趋势图分析-非小号](https://www.feixiaohao.com/currencies/scry/)，SCRY.INFO是发布的平台，2018年经历了一轮暴跌~

![image.png](https://upload-images.jianshu.io/upload_images/637344-28cd776fa1687ea1.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 小结

[SCRY符安文：沈波是我的恩人](https://www.sohu.com/a/230382149_100134346)一文所总结的：

![image.png](https://upload-images.jianshu.io/upload_images/637344-427e508969a16911.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

## 评价标准

- 区块链落地场景是否涉及协作？

就一个农产品电商平台，没看有什么落地的点。

- 上链的实体价值是否能超过上链后高昂的计算费用；

成本反而更高了，或者说基本没变，还是那样，只是换了概念。

- 如果没有区块链技术，该场景是否依旧可以落地；

原先就是做农产品电商平台的，后来改头换面后，就成了区块链公司了。

- 创新力：从共识机制创新、加密算法创新、性能和安全、生态创新几个角度是否有突破；

从公开的开源 github 仓库来看，直觉不靠谱， 且两年多不更新了。再则，食物优半死不活的状态，平台已经废了。

- 团队：团队的技术背景，以及过往经历是否可以支持对业务场景的深入理解。

业务场景涉及农业农产品这块，但团队里面压根就没这方面的人才。


## 参考

- [SCRY符安文：沈波是我的恩人](https://www.sohu.com/a/230382149_100134346)
- [人物∣分布式资本沈波：低调的大操盘手 - 知乎](https://zhuanlan.zhihu.com/p/48133075)

## ChangeLog
- 201904102345

**Comment by happylyy** [comment]
序号 | 日期 | 级别 | 估值 | 金额 | 比例 | 投资方 | 新闻来源
-- | -- | -- | -- | -- | -- | -- | --
1 | 2018-05-05 | 战略投资 | - | 未透露 |   | 普华永道 | 普华永道收购区块链服务供应商VeChain少数股权
  | 2017-11 | Pre-A轮 |   |   |   | 明势资本 | （jing-data）
2 | 2017-08-01 | Pre-A轮 | - | 金额未知 |   | 千方基金 | -
3 | 2016-08-09 | 天使轮 | - | 金额未知 | - | 分布式资本 | -
4 | 2016-01-26 | 种子轮 | - | 100万人民币 | - | 投资方未知 | Vechain（唯链）获数百万元投资，发布首个基于区块链的防伪平台

**Comment by happylyy** [comment]
## 唯链 Vechain

结论：

1. 区块链落地场景是否涉及协作；

   1. 从其落地的红酒领域并没有看到协作，也解决不了源头数据作假的问题

2. 上链的实体价值是否能超过上链后高昂的计算费用；

   1. 红酒这部分还算比较昂贵

3. 如果没有区块链技术，该场景是否依旧可以落地；

   1. 可以，由红酒生产厂家对所有数据全权负责其准确性

4. 创新力：从共识机制创新、加密算法创新、性能和安全、生态创新几个角度是否有突破；

   1. 很少专利，推测技术实力不行，全靠营销。

5. 团队：团队的技术背景，以及过往经历是否可以支持对业务场景的深入理解。

   ​	大多是企业高管背景，主要靠营销。

   1. 陆洋 CEO
   2. 顾建良 – CTO
      上海⼤学控制理论与控制⼯程专业硕⼠。曾任TCL通讯科技公司技术主管。拥有16年以上嵌⼊式系统硬、软件开发与管理经验。
   3. Noah Huo – CMO
      在⾦融技术、⽹络安全、内部控制和区块链技术领域拥有5年的管理咨询经验。曾在澳⼤利亚国家银⾏的⾦融犯罪检测和预防⼩组⼯作。
   4. 人力资源官王佳珉
   5. 首席战略官庄家栋

其他落地项目。

1. 与比亚迪合作的节能减排项目https://www.prnasia.com/story/221781-1.shtml

### 公司介绍：

成立于2014-01-06，唯链在2018-08-04 ICO上市，现在市值4亿美元。$405,439,282USD/77,362BTC   https://coinmarketcap.com/currencies/vechain/

VeChain唯链是一家区块链供应链管理服务商，以区块链技术为核心，VeChain提供一套面向全球的真假校验和透明供应链管理的解决方案以应对全球泛滥的假货问题，同时使得消费客户更加关注所购买的产品本身，包括产地，材料质地，设计理念，品牌故事等等。通过VeChain平台，产品和知识产权的关键内容可以放入到公共区块链数据库中，对产品和知识产品的保护将变得便捷和安全，而不用担心篡改和争议，世界上任何一个角落的消费者都可以通过互联网快访问速获取信息。

唯链隶属于上海鼎利信息科技有限公司，实际控制人是钱德君

维护了一个社区：https://vechainfans.com/

### 融资历程：

已经获得万向控股旗下分布式资本的投资，股东包括分布式资本创始人——沈波（2016），另外提一下，董事戴旭光就是量子链创始人帅初，帅初本人也曾担任过唯链的 CTO。

在2018-08-04 ICO上市，现在市值4亿美元。$405,439,282USD/77,362BTC   https://coinmarketcap.com/currencies/vechain/
 

![](https://upload-images.jianshu.io/upload_images/2245599-dfcd4a3b547a3b14?imageMogr2/auto-orient/strip%7CimageView2/2/w/640)
|序号 | 日期 | 级别 | 估值 | 金额 | 比例 | 投资方 | 新闻来源
|-- | -- | -- | -- | -- | -- | -- | --
|1 | 2018-05-05 | 战略投资 | - | 未透露 |   | 普华永道 | 普华永道收购区块链服务供应商VeChain少数股权
  | 2017-11 | Pre-A轮 |   |   |   | 明势资本 | （jing-data）
|2 | 2017-08-01 | Pre-A轮 | - | 金额未知 |   | 千方基金 | -
|3 | 2016-08-09 | 天使轮 | - | 金额未知 | - | 分布式资本 | -
|4 | 2016-01-26 | 种子轮 | - | 100万人民币 | - | 投资方未知 | Vechain（唯链）获数百万元投资，发布首个基于区块链的防伪平台



![](C:\Users\Neusoft\AppData\Roaming\Typora\typora-user-images\1554891568059.png)

### 知识产权

唯链的商标和专利都属于“上海唯链信息科技有限公司”（陆扬）。专利方面主要是区块链在不同行业的应用，共有24项专利。

http://www.soopat.com/Home/Result?SearchWord=%E4%B8%8A%E6%B5%B7%E5%94%AF%E9%93%BE%E4%BF%A1%E6%81%AF%E7%A7%91%E6%8A%80%E6%9C%89%E9%99%90%E5%85%AC%E5%8F%B8&FMZL=Y&SYXX=Y&WGZL=Y&FMSQ=Y

商标包括：唯链，vechain，vethor，VECHAINTHOR，VECHAINWORLD，V

![](C:\Users\Neusoft\AppData\Roaming\Typora\typora-user-images\1554892198182.png)



而唯链隶属于上海鼎利信息科技有限公司，并没有任何唯链相关的知识产权。

由此看来唯链的母公司并不掌握核心技术，而其核心技术掌握在陆扬所属的上海唯链信息科技有限公司中。



### 财务状况



找到了唯链在社区发布的财务状况

[唯链第二季度财务执行情况披露](http://www.gongxiangcj.com/coin_events/179)

[唯链第三季度财务执行状况披露](https://mp.weixin.qq.com/s?__biz=Mzg5OTA2MDkxMA==&mid=2247485239&amp;idx=1&amp;sn=bdd7a810e3b834b49528e7f7e75ffbaa&source=41#wechat_redirect)

[唯链第四季度财务执行状况披露](http://www.btb8.com/ven/1809/12867.html)

[唯链第五季度财务执行状况披露](http://m.btb8.com/ven/1812/22827.html)

[唯链第六季度财务执行状况披露](http://m.btb8.com/ven/1903/40043.html)



### 鲸准数据



产品服务

[服务]
1.以区块链技术为核心，VeChain提供一套真假校验和透明供应链管理的解决方案以应对全球泛滥的假货问题，同时使得消费用户更加关注所购买的产品本身，包括产地，材料质地，设计理念，品牌故事等等。
2.通过VeChain平台，产品和知识产权的关键内容可以放入到公共区块链数据库中，对产品和知识产品的保护将变得便捷和安全，而不用担心篡改和争议，消费者可以通过互联网快访问速获取信息。

3. 已有商业落地，商业生态圈已经初具雏形，目前唯链的客户已经覆盖多个行业，包括：时尚奢侈品行业、食品安全、汽车企业、供应链行业、农业行业等；

[解决方案]
1.酒类：通过区块链系统，在生产、运输、进口、销售各环节逐层监管产品流向，降低造假、售假现象，提升企业品牌价值。
2.奢侈品：通过商品管理平台将商品上链，物流服务方扫码操作进行物流信息上链，销售管理平台对售出商品转移所有权，最后消费者验证真伪并宣告所有权。
3.汽车：赋予汽车的唯一性ID，为每一辆汽车建立一个数字档案，并且围绕不同阶段的汽车所有权建立不同的档案权限，以应对不同的业务场景。
4.零售：品牌方在管理系统中将ID上链，消费者可以通过自己的手机与品牌方形成有效的互动，从而品牌方能够准确的获得终端消费者的真实反馈。
5.绿色农业：提供面向绿色有机农业认证的区块链专有云，将生产过程中的各类数据通过物联网或手持设备导入云平台。
6.物流：利用区块链技术，物流环节中的参与方可以在公开、匿名又不可篡改的安全平台上共享信息，从而打通整个流程的信息流。

7. 供应链物流、物联网等。比如我们跟雷诺、宝马做有关汽车方面的数据采集，将其与保险公司做对接使用；跟比亚迪、人保、光明一起做的一个碳减排的生态。”

**Comment by fishwgj** [comment]
# Skuchain
## 融资情况
- 2018.3.12 种子轮 NTT DOCOMO Ventures
- 2017.6.13 种子轮 Blockchange Ventures
- 2016.2.3 种子轮 Digital Currency Group, Amino Capital, Fenbushi Capital
## 创始人与高管团队
国际贸易背景，团队稳定
## 核心业务
- 基于区块链技术提供国际贸易金融服务 [Skuchain: Blockchain Enterprise Supply Chain For Trading](https://bitcoinexchangeguide.com/skuchain/)
- [供应链跟踪](http://www.skuchain.com/popcodes/)
## 最新案例
[National Bank of Canada, CGI, and Skuchain, Announce Pilot Program to Streamline Trade Finance with Blockchain](https://www.newsbtc.com/2018/10/23/blockchain-platform-skuchain-brings-smart-contracts-to-trade-finance-in-canada/)
