### ISSUE TITLE
朴素版BP框架

### ISSUE THREAD

**Issue by fishwgj** [livingworld/IA004_blockchain#8]
# 区块链全局认识

#### 第一代：比特币

（奠定区块链基本特征）

#### 第二代：以太坊

智能合约

提升效率

#### 第三代发展方向

共识效率

合规合法性

等。。。

### 空间：应用行业

金融

贸易

物流

文创娱乐

### 变量：关键技术

非对称加密

共识机制

去中心化

不可能三角

### 论文比较

基础研究 vs 行业应用

#### 行业比较

区块链公司主要集中在哪些行业

### GOOD-1：Skuchain

。。。。。。

### GOOD-2: XXXX

。。。。。。。

### BAD-1：步步鸡

。。。。。。。。

### BAD-2: 空气币

。。。。。。。。

## 结论：区块链公司项目评价标准

1. 商业本质逻辑
2. 业务或技术壁垒
3. 创始团队
4. 投资 or 站台大佬
5. 。。。。。

**Comment by zhongrongeven** [comment]
汗颜，发现自己和组长天大的差距~~这个框架好棒啊
